micronaut:
  application:
    name: proposta
  server:
    port: ${HTTP_SERVER_PORT:8085}

grpc:
  server:
    port: ${GRPC_SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024
  health:
    enabled: true

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
#  all:
#    port: 8085 # Rodar o health check numa porta diferente

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/proposta`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
    dialect: ${DB_DIALECT:POSTGRES}

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

analise.url: ${ANALISE_URL:`http://localhost:9999/api/solicitacao`}
cartao.url: ${CARTAO_URL:`http://localhost:8888/api/cartoes`}